// <auto-generated />
using DataAccessLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180228165542_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DataAccessLibrary.Model.Follow", b =>
                {
                    b.Property<int>("FollowID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RssItemID");

                    b.Property<int>("UserID");

                    b.HasKey("FollowID");

                    b.HasIndex("RssItemID");

                    b.HasIndex("UserID");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.RssItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Uri");

                    b.HasKey("ID");

                    b.ToTable("RssItems");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.Follow", b =>
                {
                    b.HasOne("DataAccessLibrary.Model.RssItem", "RssItem")
                        .WithMany("Follows")
                        .HasForeignKey("RssItemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAccessLibrary.Model.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
